import mongoose from "mongoose";
import dotenv from "dotenv";
import { Course } from "./models/Course.js"; // adjust path if needed

dotenv.config();

// 1️⃣ Connect to MongoDB
const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB connected successfully");
  } catch (error) {
    console.error("MongoDB connection failed:", error.message);
    process.exit(1);
  }
};

// 2️⃣ Sample courses with working images from Unsplash
const sampleCourses = [
  // Web Development Courses
  {
    title: "React for Beginners",
    description: "Learn React from scratch and build amazing web apps. Master components, hooks, and state management.",
    category: "Web Development",
    level: "Beginner",
    duration: "6 weeks",
    totalSlots: 50,
    availableSlots: 50,
    price: 499,
    thumbnailUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=dGcsHMXbSOA",
    notes: [{ title: "React Basics Notes", fileUrl: "https://example.com/react-basics.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Advanced React & Next.js",
    description: "Take your React skills to the next level with Next.js, server components, and advanced patterns.",
    category: "Web Development",
    level: "Advanced",
    duration: "8 weeks",
    totalSlots: 40,
    availableSlots: 40,
    price: 699,
    thumbnailUrl: "https://images.unsplash.com/photo-1555066937-4365d14bab8c?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=7CqJlxBYj-M",
    notes: [{ title: "Next.js Notes", fileUrl: "https://example.com/nextjs.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Vue.js - The Complete Guide",
    description: "Build reactive web apps with Vue.js, Vuex, and Vue Router. Perfect for beginners.",
    category: "Web Development",
    level: "Beginner",
    duration: "7 weeks",
    totalSlots: 45,
    availableSlots: 45,
    price: 549,
    thumbnailUrl: "https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=4deVCNJq3qc",
    notes: [{ title: "Vue.js Notes", fileUrl: "https://example.com/vue.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Angular - Zero to Hero",
    description: "Master Angular framework, TypeScript, and build enterprise-grade applications.",
    category: "Web Development",
    level: "Intermediate",
    duration: "9 weeks",
    totalSlots: 35,
    availableSlots: 35,
    price: 649,
    thumbnailUrl: "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=3qBXWUpoPHo",
    notes: [{ title: "Angular Notes", fileUrl: "https://example.com/angular.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "HTML5 & CSS3 Masterclass",
    description: "Build responsive websites with modern HTML5, CSS3, Flexbox, and Grid.",
    category: "Web Development",
    level: "Beginner",
    duration: "5 weeks",
    totalSlots: 60,
    availableSlots: 60,
    price: 399,
    thumbnailUrl: "https://images.unsplash.com/photo-1547658719-da2b51169166?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=mU6anWqZJcc",
    notes: [{ title: "HTML CSS Notes", fileUrl: "https://example.com/html-css.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "JavaScript - The Complete Guide",
    description: "Modern JavaScript from basics to advanced. ES6+, async/await, and design patterns.",
    category: "Web Development",
    level: "Intermediate",
    duration: "8 weeks",
    totalSlots: 55,
    availableSlots: 55,
    price: 599,
    thumbnailUrl: "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=PkZNo7MFNFg",
    notes: [{ title: "JavaScript Notes", fileUrl: "https://example.com/js.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },

  // Backend Development Courses
  {
    title: "Node.js & Express Masterclass",
    description: "Build REST APIs and full-stack apps using Node.js and Express with MongoDB.",
    category: "Backend Development",
    level: "Intermediate",
    duration: "8 weeks",
    totalSlots: 40,
    availableSlots: 40,
    price: 599,
    thumbnailUrl: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=Oe421EPjeBE",
    notes: [{ title: "Express Notes", fileUrl: "https://example.com/express.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Python Django - Web Development",
    description: "Build robust web applications with Python Django framework and SQLite.",
    category: "Backend Development",
    level: "Beginner",
    duration: "9 weeks",
    totalSlots: 35,
    availableSlots: 35,
    price: 649,
    thumbnailUrl: "https://images.unsplash.com/photo-1526379095098-400a3a224a7a?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=F5mRW0jo-U4",
    notes: [{ title: "Django Notes", fileUrl: "https://example.com/django.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Java Spring Boot",
    description: "Build enterprise microservices with Spring Boot, JPA, and REST APIs.",
    category: "Backend Development",
    level: "Advanced",
    duration: "10 weeks",
    totalSlots: 30,
    availableSlots: 30,
    price: 799,
    thumbnailUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=9SGDpanrc8U",
    notes: [{ title: "Spring Boot Notes", fileUrl: "https://example.com/spring.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Go Lang - The Complete Course",
    description: "Learn Go programming language, concurrency patterns, and build high-performance APIs.",
    category: "Backend Development",
    level: "Intermediate",
    duration: "7 weeks",
    totalSlots: 35,
    availableSlots: 35,
    price: 599,
    thumbnailUrl: "https://images.unsplash.com/photo-1623479322729-28b25c16b011?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=YS4e4q9oBaU",
    notes: [{ title: "Go Notes", fileUrl: "https://example.com/go.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "PHP & Laravel Masterclass",
    description: "Build modern web apps with PHP 8 and Laravel framework.",
    category: "Backend Development",
    level: "Beginner",
    duration: "8 weeks",
    totalSlots: 40,
    availableSlots: 40,
    price: 549,
    thumbnailUrl: "https://images.unsplash.com/photo-1523803326055-72a13a0c7d63?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=ImtZ5yENzgU",
    notes: [{ title: "Laravel Notes", fileUrl: "https://example.com/laravel.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "GraphQL with Node.js",
    description: "Build flexible APIs with GraphQL, Apollo Server, and React.",
    category: "Backend Development",
    level: "Advanced",
    duration: "6 weeks",
    totalSlots: 30,
    availableSlots: 30,
    price: 699,
    thumbnailUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=ed8SzALpx1Q",
    notes: [{ title: "GraphQL Notes", fileUrl: "https://example.com/graphql.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },

  // Data Science & AI
  {
    title: "Python for Data Science",
    description: "Master Python, NumPy, Pandas, and data visualization for data analysis.",
    category: "Data Science",
    level: "Beginner",
    duration: "8 weeks",
    totalSlots: 45,
    availableSlots: 45,
    price: 649,
    thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=LHBE6Q9XlzI",
    notes: [{ title: "Python Data Science Notes", fileUrl: "https://example.com/pydata.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Machine Learning A-Z",
    description: "Learn ML algorithms with Python, scikit-learn, and TensorFlow.",
    category: "Data Science",
    level: "Intermediate",
    duration: "12 weeks",
    totalSlots: 40,
    availableSlots: 40,
    price: 899,
    thumbnailUrl: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=Gv9_4yMHFhI",
    notes: [{ title: "ML Notes", fileUrl: "https://example.com/ml.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Deep Learning Specialization",
    description: "Master neural networks, CNNs, RNNs with PyTorch and TensorFlow.",
    category: "Data Science",
    level: "Advanced",
    duration: "14 weeks",
    totalSlots: 25,
    availableSlots: 25,
    price: 999,
    thumbnailUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=VyWAvY2CF9c",
    notes: [{ title: "Deep Learning Notes", fileUrl: "https://example.com/dl.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },

  // Cloud Computing
  {
    title: "AWS Certified Solutions Architect",
    description: "Master AWS services, architecture, and pass the certification exam.",
    category: "Cloud Computing",
    level: "Intermediate",
    duration: "10 weeks",
    totalSlots: 35,
    availableSlots: 35,
    price: 799,
    thumbnailUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=Ia-UEYYR44s",
    notes: [{ title: "AWS Notes", fileUrl: "https://example.com/aws.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Docker & Kubernetes",
    description: "Containerize apps with Docker and orchestrate with Kubernetes.",
    category: "Cloud Computing",
    level: "Intermediate",
    duration: "6 weeks",
    totalSlots: 40,
    availableSlots: 40,
    price: 649,
    thumbnailUrl: "https://images.unsplash.com/photo-1605745341112-85968b19335b?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=X48VuDVv0do",
    notes: [{ title: "Docker Notes", fileUrl: "https://example.com/docker.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Microsoft Azure Fundamentals",
    description: "Learn Azure cloud services, virtual machines, and storage solutions.",
    category: "Cloud Computing",
    level: "Beginner",
    duration: "6 weeks",
    totalSlots: 45,
    availableSlots: 45,
    price: 599,
    thumbnailUrl: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=NKEFWyqJ5XA",
    notes: [{ title: "Azure Notes", fileUrl: "https://example.com/azure.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },

  // Mobile Development
  {
    title: "React Native - Build Mobile Apps",
    description: "Build iOS and Android apps with React Native and Expo.",
    category: "Mobile Development",
    level: "Intermediate",
    duration: "9 weeks",
    totalSlots: 40,
    availableSlots: 40,
    price: 699,
    thumbnailUrl: "https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=0-S5a0eXPoc",
    notes: [{ title: "React Native Notes", fileUrl: "https://example.com/rn.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Flutter & Dart - The Complete Guide",
    description: "Build beautiful native apps with Flutter and Dart for iOS & Android.",
    category: "Mobile Development",
    level: "Beginner",
    duration: "10 weeks",
    totalSlots: 45,
    availableSlots: 45,
    price: 749,
    thumbnailUrl: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=VPvVD8t02U8",
    notes: [{ title: "Flutter Notes", fileUrl: "https://example.com/flutter.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "iOS Development with Swift",
    description: "Build iOS apps with SwiftUI, UIKit, and Core Data.",
    category: "Mobile Development",
    level: "Intermediate",
    duration: "12 weeks",
    totalSlots: 30,
    availableSlots: 30,
    price: 849,
    thumbnailUrl: "https://images.unsplash.com/photo-1618389041494-8fab89c3f22b?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=09TeUXjzpKs",
    notes: [{ title: "iOS Notes", fileUrl: "https://example.com/ios.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },

  // DevOps
  {
    title: "DevOps Bootcamp",
    description: "Master CI/CD, Jenkins, GitOps, and infrastructure as code.",
    category: "DevOps",
    level: "Intermediate",
    duration: "8 weeks",
    totalSlots: 35,
    availableSlots: 35,
    price: 749,
    thumbnailUrl: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=hQcFE0RD0cQ",
    notes: [{ title: "DevOps Notes", fileUrl: "https://example.com/devops.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Terraform - Infrastructure as Code",
    description: "Automate cloud infrastructure with Terraform across AWS, Azure, GCP.",
    category: "DevOps",
    level: "Advanced",
    duration: "5 weeks",
    totalSlots: 30,
    availableSlots: 30,
    price: 599,
    thumbnailUrl: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=7xngnjfIlK4",
    notes: [{ title: "Terraform Notes", fileUrl: "https://example.com/terraform.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Jenkins CI/CD Pipeline",
    description: "Build automated CI/CD pipelines with Jenkins, Docker, and GitHub.",
    category: "DevOps",
    level: "Intermediate",
    duration: "4 weeks",
    totalSlots: 40,
    availableSlots: 40,
    price: 499,
    thumbnailUrl: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=6YZvp2GwT0A",
    notes: [{ title: "Jenkins Notes", fileUrl: "https://example.com/jenkins.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },

  // Cybersecurity
  {
    title: "Ethical Hacking Fundamentals",
    description: "Learn penetration testing, vulnerability assessment, and security tools.",
    category: "Cybersecurity",
    level: "Beginner",
    duration: "8 weeks",
    totalSlots: 35,
    availableSlots: 35,
    price: 699,
    thumbnailUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=3Kq1MIfTWCE",
    notes: [{ title: "Ethical Hacking Notes", fileUrl: "https://example.com/hacking.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Network Security & Cryptography",
    description: "Secure networks, implement encryption, and protect against attacks.",
    category: "Cybersecurity",
    level: "Intermediate",
    duration: "7 weeks",
    totalSlots: 30,
    availableSlots: 30,
    price: 649,
    thumbnailUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=J4wKU6Vn4KQ",
    notes: [{ title: "Network Security Notes", fileUrl: "https://example.com/network.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },

  // Database
  {
    title: "MongoDB - The Complete Guide",
    description: "Master MongoDB, aggregation framework, and database design.",
    category: "Database",
    level: "Intermediate",
    duration: "6 weeks",
    totalSlots: 45,
    availableSlots: 45,
    price: 549,
    thumbnailUrl: "https://images.unsplash.com/photo-1623479322729-28b25c16b011?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=VELru-FCWDM",
    notes: [{ title: "MongoDB Notes", fileUrl: "https://example.com/mongodb.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "SQL & PostgreSQL Masterclass",
    description: "Master SQL queries, database design, and PostgreSQL optimization.",
    category: "Database",
    level: "Beginner",
    duration: "7 weeks",
    totalSlots: 50,
    availableSlots: 50,
    price: 499,
    thumbnailUrl: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=zw4s3Ey8AYM",
    notes: [{ title: "SQL Notes", fileUrl: "https://example.com/sql.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },

  // UI/UX Design
  {
    title: "Figma - UI/UX Design",
    description: "Design beautiful interfaces and prototypes with Figma.",
    category: "UI/UX Design",
    level: "Beginner",
    duration: "5 weeks",
    totalSlots: 55,
    availableSlots: 55,
    price: 449,
    thumbnailUrl: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=FTFaQWZBqQ8",
    notes: [{ title: "Figma Notes", fileUrl: "https://example.com/figma.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "UX Research & Strategy",
    description: "Master user research, wireframing, and usability testing.",
    category: "UI/UX Design",
    level: "Intermediate",
    duration: "6 weeks",
    totalSlots: 40,
    availableSlots: 40,
    price: 599,
    thumbnailUrl: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=J_uvMvU5n7M",
    notes: [{ title: "UX Notes", fileUrl: "https://example.com/ux.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },

  // Business
  {
    title: "Digital Marketing Masterclass",
    description: "Learn SEO, social media marketing, Google Ads, and analytics.",
    category: "Business",
    level: "Beginner",
    duration: "8 weeks",
    totalSlots: 60,
    availableSlots: 60,
    price: 599,
    thumbnailUrl: "https://images.unsplash.com/photo-1557838923-2985c318be48?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=lx3xNsUvQbA",
    notes: [{ title: "Marketing Notes", fileUrl: "https://example.com/marketing.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
  {
    title: "Product Management 101",
    description: "Master product lifecycle, agile methodologies, and roadmapping.",
    category: "Business",
    level: "Intermediate",
    duration: "6 weeks",
    totalSlots: 45,
    availableSlots: 45,
    price: 649,
    thumbnailUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop",
    youtubeUrl: "https://www.youtube.com/watch?v=tuDnIq7Qk6A",
    notes: [{ title: "PM Notes", fileUrl: "https://example.com/pm.pdf" }],
    createdBy: "user_39hQwF1quvp25HnBqyqetd58xA4",
    isPublished: true,
  },
];

// 3️⃣ Insert sample data
const insertSampleCourses = async () => {
  try {
    // Clear existing courses
    await Course.deleteMany({});
    console.log("Existing courses cleared");

    // Insert new courses
    const createdCourses = await Course.insertMany(sampleCourses);
    console.log(`✅ ${createdCourses.length} sample courses inserted successfully:`);
    
    // Group by category for summary
    const summary = createdCourses.reduce((acc, course) => {
      acc[course.category] = (acc[course.category] || 0) + 1;
      return acc;
    }, {});

    console.log("\n📊 Courses by category:");
    Object.entries(summary).forEach(([category, count]) => {
      console.log(`   ${category}: ${count} courses`);
    });

    console.log("\n📝 Sample course titles:");
    createdCourses.slice(0, 10).forEach((course) => console.log(`   • ${course.title}`));
    console.log(`   ... and ${createdCourses.length - 10} more`);

    process.exit(0);
  } catch (error) {
    console.error("❌ Error inserting sample courses:", error.message);
    process.exit(1);
  }
};

// 4️⃣ Run
connectDB().then(insertSampleCourses);